/*
 * BrexitElectionAreas
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/30/2016
 */
package localhost8080.interfaces;

import java.util.*;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import localhost8080.models.*;

public interface AreasInterface {
    /**
     * List all the EU election Areas
     * @param    limit    Optional parameter: How many items to return at one time (max 100)
	 * @return	Returns the List<AreaObject> response from the API call*/
    @GET
    @Path("/areas")
    @Produces(MediaType.APPLICATION_JSON)
    public List<AreaObject> listAreasAsync(
            @QueryParam("limit") Integer limit);
}