/*
 * BrexitElectionAreas
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/30/2016
 */
package localhost8080.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AreaObject 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5259296711675583501L;
    private String identity;
    private String gss;
    private String ons;
    private String unitId;
    private String mapItId;
    private String areaTypeCode;
    private String areaTypeName;
    private String name;
    private String country;
    private String regionName;
    private String regionCode;
    private String latitudeMiddle;
    private String longitudeMiddle;
    private String latitudeMinimum;
    private String latitudeMaximum;
    private String longitudeMinimum;
    private String longitudeMaximum;
    private Double areaSize;
    private Integer electorate;
    private Integer registered;
    private Integer validVotes;
    private Integer leaveVotes;
    private Integer remainVotes;
    private Integer totalPopulation;
    private Integer malePopulation;
    private String femalePopulation;
    /** GETTER
     * The unique identity of an Area
     */
    @JsonGetter("identity")
    public String getIdentity ( ) { 
        return this.identity;
    }
    
    /** SETTER
     * The unique identity of an Area
     */
    @JsonSetter("identity")
    public void setIdentity (String value) { 
        this.identity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("gss")
    public String getGss ( ) { 
        return this.gss;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("gss")
    public void setGss (String value) { 
        this.gss = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ons")
    public String getOns ( ) { 
        return this.ons;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ons")
    public void setOns (String value) { 
        this.ons = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("unitId")
    public String getUnitId ( ) { 
        return this.unitId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("unitId")
    public void setUnitId (String value) { 
        this.unitId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mapItId")
    public String getMapItId ( ) { 
        return this.mapItId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mapItId")
    public void setMapItId (String value) { 
        this.mapItId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("areaTypeCode")
    public String getAreaTypeCode ( ) { 
        return this.areaTypeCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("areaTypeCode")
    public void setAreaTypeCode (String value) { 
        this.areaTypeCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("areaTypeName")
    public String getAreaTypeName ( ) { 
        return this.areaTypeName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("areaTypeName")
    public void setAreaTypeName (String value) { 
        this.areaTypeName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("regionName")
    public String getRegionName ( ) { 
        return this.regionName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("regionName")
    public void setRegionName (String value) { 
        this.regionName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("regionCode")
    public String getRegionCode ( ) { 
        return this.regionCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("regionCode")
    public void setRegionCode (String value) { 
        this.regionCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("latitudeMiddle")
    public String getLatitudeMiddle ( ) { 
        return this.latitudeMiddle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("latitudeMiddle")
    public void setLatitudeMiddle (String value) { 
        this.latitudeMiddle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("longitudeMiddle")
    public String getLongitudeMiddle ( ) { 
        return this.longitudeMiddle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("longitudeMiddle")
    public void setLongitudeMiddle (String value) { 
        this.longitudeMiddle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("latitudeMinimum")
    public String getLatitudeMinimum ( ) { 
        return this.latitudeMinimum;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("latitudeMinimum")
    public void setLatitudeMinimum (String value) { 
        this.latitudeMinimum = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("latitudeMaximum")
    public String getLatitudeMaximum ( ) { 
        return this.latitudeMaximum;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("latitudeMaximum")
    public void setLatitudeMaximum (String value) { 
        this.latitudeMaximum = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("longitudeMinimum")
    public String getLongitudeMinimum ( ) { 
        return this.longitudeMinimum;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("longitudeMinimum")
    public void setLongitudeMinimum (String value) { 
        this.longitudeMinimum = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("longitudeMaximum")
    public String getLongitudeMaximum ( ) { 
        return this.longitudeMaximum;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("longitudeMaximum")
    public void setLongitudeMaximum (String value) { 
        this.longitudeMaximum = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("areaSize")
    public Double getAreaSize ( ) { 
        return this.areaSize;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("areaSize")
    public void setAreaSize (Double value) { 
        this.areaSize = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("electorate")
    public Integer getElectorate ( ) { 
        return this.electorate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("electorate")
    public void setElectorate (Integer value) { 
        this.electorate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("registered")
    public Integer getRegistered ( ) { 
        return this.registered;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("registered")
    public void setRegistered (Integer value) { 
        this.registered = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("validVotes")
    public Integer getValidVotes ( ) { 
        return this.validVotes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("validVotes")
    public void setValidVotes (Integer value) { 
        this.validVotes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leaveVotes")
    public Integer getLeaveVotes ( ) { 
        return this.leaveVotes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leaveVotes")
    public void setLeaveVotes (Integer value) { 
        this.leaveVotes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("remainVotes")
    public Integer getRemainVotes ( ) { 
        return this.remainVotes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("remainVotes")
    public void setRemainVotes (Integer value) { 
        this.remainVotes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("totalPopulation")
    public Integer getTotalPopulation ( ) { 
        return this.totalPopulation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("totalPopulation")
    public void setTotalPopulation (Integer value) { 
        this.totalPopulation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("malePopulation")
    public Integer getMalePopulation ( ) { 
        return this.malePopulation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("malePopulation")
    public void setMalePopulation (Integer value) { 
        this.malePopulation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("femalePopulation")
    public String getFemalePopulation ( ) { 
        return this.femalePopulation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("femalePopulation")
    public void setFemalePopulation (String value) { 
        this.femalePopulation = value;
    }
 
}
 