/*
 * BrexitElectionAreas
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/30/2016
 */
package localhost8080.models;

import java.util.*;

public class AreaObjectBuilder {
    //the instance to build
    private AreaObject areaObject;

    /**
     * Default constructor to initialize the instance
     */
    public AreaObjectBuilder() {
        areaObject = new AreaObject();
    }

    /**
     * The unique identity of an Area
     */
    public AreaObjectBuilder identity(String identity) {
        areaObject.setIdentity(identity);
        return this;
    }

    public AreaObjectBuilder gss(String gss) {
        areaObject.setGss(gss);
        return this;
    }

    public AreaObjectBuilder ons(String ons) {
        areaObject.setOns(ons);
        return this;
    }

    public AreaObjectBuilder unitId(String unitId) {
        areaObject.setUnitId(unitId);
        return this;
    }

    public AreaObjectBuilder mapItId(String mapItId) {
        areaObject.setMapItId(mapItId);
        return this;
    }

    public AreaObjectBuilder areaTypeCode(String areaTypeCode) {
        areaObject.setAreaTypeCode(areaTypeCode);
        return this;
    }

    public AreaObjectBuilder areaTypeName(String areaTypeName) {
        areaObject.setAreaTypeName(areaTypeName);
        return this;
    }

    public AreaObjectBuilder name(String name) {
        areaObject.setName(name);
        return this;
    }

    public AreaObjectBuilder country(String country) {
        areaObject.setCountry(country);
        return this;
    }

    public AreaObjectBuilder regionName(String regionName) {
        areaObject.setRegionName(regionName);
        return this;
    }

    public AreaObjectBuilder regionCode(String regionCode) {
        areaObject.setRegionCode(regionCode);
        return this;
    }

    public AreaObjectBuilder latitudeMiddle(String latitudeMiddle) {
        areaObject.setLatitudeMiddle(latitudeMiddle);
        return this;
    }

    public AreaObjectBuilder longitudeMiddle(String longitudeMiddle) {
        areaObject.setLongitudeMiddle(longitudeMiddle);
        return this;
    }

    public AreaObjectBuilder latitudeMinimum(String latitudeMinimum) {
        areaObject.setLatitudeMinimum(latitudeMinimum);
        return this;
    }

    public AreaObjectBuilder latitudeMaximum(String latitudeMaximum) {
        areaObject.setLatitudeMaximum(latitudeMaximum);
        return this;
    }

    public AreaObjectBuilder longitudeMinimum(String longitudeMinimum) {
        areaObject.setLongitudeMinimum(longitudeMinimum);
        return this;
    }

    public AreaObjectBuilder longitudeMaximum(String longitudeMaximum) {
        areaObject.setLongitudeMaximum(longitudeMaximum);
        return this;
    }

    public AreaObjectBuilder areaSize(Double areaSize) {
        areaObject.setAreaSize(areaSize);
        return this;
    }

    public AreaObjectBuilder electorate(Integer electorate) {
        areaObject.setElectorate(electorate);
        return this;
    }

    public AreaObjectBuilder registered(Integer registered) {
        areaObject.setRegistered(registered);
        return this;
    }

    public AreaObjectBuilder validVotes(Integer validVotes) {
        areaObject.setValidVotes(validVotes);
        return this;
    }

    public AreaObjectBuilder leaveVotes(Integer leaveVotes) {
        areaObject.setLeaveVotes(leaveVotes);
        return this;
    }

    public AreaObjectBuilder remainVotes(Integer remainVotes) {
        areaObject.setRemainVotes(remainVotes);
        return this;
    }

    public AreaObjectBuilder totalPopulation(Integer totalPopulation) {
        areaObject.setTotalPopulation(totalPopulation);
        return this;
    }

    public AreaObjectBuilder malePopulation(Integer malePopulation) {
        areaObject.setMalePopulation(malePopulation);
        return this;
    }

    public AreaObjectBuilder femalePopulation(String femalePopulation) {
        areaObject.setFemalePopulation(femalePopulation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AreaObject build() {
        return areaObject;
    }
}